version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/moments
permissions:
  - object: /home/ubuntu/moments/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh