version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/moments
permissions:
  - object: /home/ubuntu/moments/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/run_new_was.sh
      timeout: 120
    - location: scripts/health_check.sh
      timeout: 120
    - location: scripts/switch.sh
      timeout: 120