spring:
  profiles:
    include: secret
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: create

cloud:
  aws:
    s3:
      bucket: moment-photo
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2S26HGZEXEBJBWND
      secret-key: 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
logging.level:
  org.hibernate.SQL: debug


